### PR TITLE
Update eclipse-atl.jsonnet

### PR DESCRIPTION
**Pull request by dwagelaar**
Branch protection breaks self-approval of PRs

See also https://github.com/orgs/community/discussions/6292

### CODE REVIEW

**Comment by netomi** [comment]
you cant self-approve your own PRs however you could set the approval count to 0. You would still benefit that you cant force push changes to the branch which we ultimately wanna prevent.

**Comment by netomi** [comment]
in order to set the approval count to 0, you can just change the snippet to the following:

```
      orgs.newBranchProtectionRule('master') {
         required_approving_review_count: 0,
      },
```

**Comment by dwagelaar** [comment]
@netomi Thanks for the tip! I've updated this PR accordingly...

**Comment by netomi** [comment]
as the PR does not delete any resource anymore, you can merge it yourself by adding `/otterdog merge` as comment.
Once its merged, it gets automatically applied, so you dont have to wait for anybody applying the changes.

**Pull request merged**
